### ISSUE TITLE
If monitor.history = 0 then crash on mail receive

### ISSUE THREAD

**Issue by chaneegonnarich** [jhillyerd/inbucket#61]
(Sorry to poor english)
Setting the " monitor.history " item to 0 causes an error when receiving mail.

```
2017/12/05 04:38:58 [INFO ] SMTP[*.*.*.*]<1> Mail from: ~~~@~~~
2017/12/05 04:38:58 [INFO ] SMTP[*.*.*.*]<1> Recipient: ###@###
2017/12/05 04:38:58 [INFO ] SMTP[*.*.*.*]<1> Message size 20068 bytes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4a45ae]

goroutine 10 [running]:
panic(0x7ee780, 0xc420012060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/jhillyerd/inbucket/msghub.(*Hub).Dispatch.func1(0xc420176a00)
        /home/james/go/src/github.com/jhillyerd/inbucket/msghub/hub.go:67 +0xae
github.com/jhillyerd/inbucket/msghub.New.func1(0xa40260, 0xc42000de00, 0xc420176a00)
        /home/james/go/src/github.com/jhillyerd/inbucket/msghub/hub.go:54 +0x112
created by github.com/jhillyerd/inbucket/msghub.New
        /home/james/go/src/github.com/jhillyerd/inbucket/msghub/hub.go:57 +0x122
```

Personally, I don't want to use history, but I think msgHub.go needs exception catch.

**Comment by jhillyerd** [comment]
Thanks for the report.  For now, set monitor.visible=false to hide the monitor UI, and history size of 1.
